services:
  sftp:
    image: atmoz/sftp
    container_name: sftp
    networks:
      app-net:
        aliases:
          # for containers, sftp host is accessible as `sftp`: `ssh foo@sftp`
          - sftp
    volumes:
      # add `/testcontainers` writable folder, and mount it to our /target/sftp/testcontainers folder
      # if you do not create this folder by yourself, docker creates it with `root` permissions
      # `mkdir -p target/sftp/testcontainers`
      - ./target/sftp/testcontainers:/home/foo/upload/testcontainers
      # to keep the same host key for connection
      - ./src/test/resources/ssh/id_ed25519_sftp1_container:/etc/ssh/ssh_host_ed25519_key
      - ./src/test/resources/ssh/id_ed25519_sftp1_container.pub:/home/foo/.ssh/keys/id_ed25519_client.pub
    ports:
      # host port : container port
      - "22:22"
    command: foo:pass:::upload

  app:
    image: 'app:latest'
    build:
      context: .
    container_name: app
    networks:
      - app-net
    volumes:
      - ./src/test/resources/external.config.4.docker.compose.yaml:/etc/dim/external.config.yaml
      # `known_hosts` contains sftp host key, to avoid manual adding of this key, each time after container gets created
      - ./src/test/resources/known_hosts:/root/.ssh/known_hosts
    ports:
      - "8080:8080"
      - "8787:8787"
    environment:
      - SPRING_CONFIG_IMPORT=file:/etc/dim/external.config.yaml
      - JAVA_OPTS=-agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=*:8787
      - JAVA_TOOL_OPTIONS=
          -Dserver.servlet.context-path=
          -DLOGGED_APPLICATION_NAME="Sftp Demo App"

networks:
  app-net: